package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Bigdata2_HttpsGithubComIyanke712121b'
in the project with id = 'Bigdata2', and delete the patch script.
*/
create(RelativeId("Bigdata2"), GitVcsRoot({
    id("Bigdata2_HttpsGithubComIyanke712121b")
    name = "https://github.com/iyanke/712121B"
    url = "https://github.com/iyanke/712121B"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "iyanke"
        password = "credentialsJSON:ba708af7-07c1-4c5f-994a-c1d2411c6a9a"
    }
}))

