package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Bigdata1_HttpsGithubComIyanke71212a'
in the project with id = 'Bigdata1', and delete the patch script.
*/
create(RelativeId("Bigdata1"), GitVcsRoot({
    id("Bigdata1_HttpsGithubComIyanke71212a")
    name = "https://github.com/iyanke/71212a"
    url = "https://github.com/iyanke/71212a"
    branch = "refs/heads/main"
    authMethod = password {
        userName = "iyanke"
        password = "credentialsJSON:ba708af7-07c1-4c5f-994a-c1d2411c6a9a"
    }
}))

